### PR TITLE
More support for NFS: World

### PR DESCRIPTION
**Pull request by berkay2578**
Getting access to _mSelf_ might be tough as it's defined within the gameplay context. You got anything with that yet?

### CODE REVIEW

**Comment by DennisStanistan** [comment]
The pull request is incredible because we basically did the exact same things lol

> Getting access to mSelf might be tough as it's defined within the gameplay context. You got anything with that yet?

I've seen it everywhere but right now I am clueless on how one would get `mSelf`.

**Comment by berkay2578** [comment]
So `mSelf` is a pointer to memory chunk and World uses PPMalloc: https://github.com/kitsilanosoftware/PPMalloc (another one: https://github.com/questor/eastl/tree/master/PPMalloc, or you can extract your own from http://gpl.ea.com).
e.g.: `NFSCars_PP':'PPMalloc':'[size = 50M, pagesize= 1M, permanent=0]`, look at 0x61BCA0 for more.

I've looked into some no-parameter mSelf assignments and it generally goes like(this is from `Vector3(_x,_y,_z)`):
```
int __cdecl sub_6853A0(int x, int y, int z)
{
  int result; // eax ~1
  //12 = heap size, 4->8->12 (x->y->z)
  result = sub_61C2A0(12, 0, dword_C817B4, 1, 0, 0);
  if ( result )
  {
    *(_DWORD *)result = x;
    *(_DWORD *)(result + 4) = y;
    *(_DWORD *)(result + 8) = z;
  }
  else
  {
    result = 0;
  }
  return result;
}
```
```
int __cdecl sub_61C2A0(int a1, char *Source, int a3, int a4, int a5, int a6)
{
  int v6; // eax ~2

  if ( dword_C81790 == -1 ) // if PAlloc isn't initiliazed
  {
    sub_61BCA0(); // init PAlloc
    v6 = a3; // have no idea what's going on here ->
    if ( a3 == -1 )
      v6 = dword_C8178C;
  }
  else
  {
    v6 = a3;
  }
  return sub_90FCD0(a1, v6, Source, a4, a5, a6);
}
```
So, here, 90FCD0 calls a PAlloc function and it uses a formula for cave location:
```
int __cdecl sub_90FCD0(int a1, int a2, char *Source, int a4, int a5, int a6)
{
  return sub_90FA20((int)Base + 512 * a2 + 67372, a1, Source, a4, a5, a6);
}
```
I've hooked it up with Olly and voila, struct definition inside the memory! However, this also means we are still limited to new creations. With this, you can call SpawnTraffic or SpawnCops from GameCore.Scripting since CoordSys is now achievable but we still can't find references to already existing things (like entirety of `Attrib.Gen`). You probably already knew this stuff but I thought some pseudo-code might help you.

Cheers!

**Comment by DennisStanistan** [comment]
I knew this stuff but this will definitely help!
I took a look at the Vector3 class inside gameplay.dll and implemented a class called `ExposedBase`
```cs
    public class ExposedBase
    {
        /// <summary>
        /// 
        /// </summary>
        public IntPtr mSelf;

        /// <summary>
        /// 
        /// </summary>
        public ExposedBase()
        { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="mSelf"></param>
        public ExposedBase(IntPtr mSelf)
        {
            this.mSelf = mSelf;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public unsafe void* _GetRaw()
        {
            return this.mSelf.ToPointer();
        }
// etc
}
```

I figured out that a binding allocates a Vector3 inside the game memory.

```cs
    public class EAVector3 : ExposedBase
    {
        /// <summary>
        /// 
        /// </summary>
        public EAVector3()
        {
            mSelf = (IntPtr)CallBinding<IntPtr>(_EASharpBinding_627);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        /// <param name="z"></param>
        public EAVector3(float x, float y, float z) : base()
        {
            mSelf = (IntPtr)CallBinding<IntPtr>(_EASharpBinding_628, x, y, z);
        }

        /// <summary>
        /// Experimental.
        /// </summary>
        public void Destory()
        {
            CallBinding(_EASharpBinding_626, mSelf);
            mSelf = IntPtr.Zero;
        }
    }
```
Then I tried to call the function `SpawnCop`

```cs
CallBinding(_EASharpBinding_53, vehicleKey, position.mSelf, position.mSelf);
```

I called the function but I don't know if it works or not, I mean the game would've crashed if I did something wrong. I don't know how to get the vehicle keys though.

**Comment by berkay2578** [comment]
```
// GameCore.Hash
public unsafe static uint Hash32(string text)
{
	int byteCount = Encoding.ASCII.GetByteCount(text);
	byte[] array = new byte[byteCount + 1];
	Encoding.ASCII.GetBytes(text, 0, byteCount, array, 0);
	array[byteCount] = 0;
	fixed (byte* ptr = array)
	{
		return Hash._EASharpBinding_94((sbyte*)ptr);
	}
}

```

**Comment by DennisStanistan** [comment]
Thanks!

**Comment by berkay2578** [comment]
You can use this to see your coordinates in-game: https://github.com/berkay2578/NFSWorldGPS I think  `setCoordinates` is broken.

**Comment by DennisStanistan** [comment]
Thanks, however I need the base address you had in order to use it.

**Pull request merged**
