### PR TITLE
More NFS: World Support and VAMemory Overhaul

### PR DESCRIPTION
**Pull request by berkay2578**
I'm just gonna start naming these with numbers since English doesn't allow anything higher than 'even more' D: I'll add more stuff later.

### World namespace changes
- Added `World.TrafficLevel`
- Added `Player.DisableAutoDrive()`.
- Added `Player.EnableAutoDrive()`.
- Added `Player.Car.position`.
- Modified `Player.Car.speed` so it's no longer read-only.
- Added `Player.Car.gravity`.
- Added `Player.Car.weight`.
- Added `Player.Car.velocityTowardsEast`.
- Added `Player.Car.velocityTowardsSouth`.
- Added `Player.Car.verticalVelocity`.
- Added `Player.Car.angularVelocity`.
- Added `Player.Car.ForceStop()`.
- Added `Player.Car.PushNorth(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.PushWest(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.PushEast(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.PushSouth(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.Hop()`.
- Added `Player.Car.ForceJump(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.TurnClockwise(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.TurnCounterclockwise(float amountOfForce, bool resetWhenSetting)`.
- Added `Player.Car.DisableWallCollisions()`.
- Added `Player.Car.EnableWallCollisions()`.
- Added `Player.Car.DisableCarCollision()`.
- Added `Player.Car.EnableCarCollision()`.
- Added `Player.Powerups.EnablePowerupCooldown()`.
- Added `Player.Powerups.DisablePowerupCooldown()`.
- Fixed ambiguity between different address definitions (´NON_STATIC_X => NONSTATIC_X`).

### NFSScript namespace changes
Be sure to take a look at these, as I know %100 you'll not like it if you just let them pass.
- (VAMemory) Completely overhauled VAMemory, it now utilizes generic Read<T> and Write<T> functions.
- (Mathf) Removed the multiple speed measurement conversion functions.
- (Mathf) Added `public static float ConvertSpeed(float, SpeedMeasurementConversionTypes)`.
- (Mathf) Added `public static float Abs(float number)` because I didn't want to import `System.Math` for one function.

### CODE REVIEW

**Comment by DennisStanistan** [comment]
This is a wonderful pull request, however I suspect that the memory additions will break other ReadFloats present that access static addresses in NFSScript. I'll accept the pull request and clean stuff up once I have the time to do so. Thanks!

**Comment by berkay2578** [comment]
I can revamp the whole VAMemory if you want, I got nothing but time.

**Comment by DennisStanistan** [comment]
> I can revamp the whole VAMemory if you want, I got nothing but time.
>
>Edit 1: Read<T>() works exactly the same way as ReadX(), NFS: World tests return same values.
>Edit 2: Write<T>() works exactly the same way as WriteX(), NFS: World tests give same results.
>Edit 3: Updating the main post.

I wouldn't recommend a single function for every type like Read<T> or Write<T> since it can slow down the reading & writing times, I mean it wouldn't slow down memory reading and writing by a significant amount but I rather have it run fast as possible than having a simple & pretty function plus it is much faster when splitting them to single functions like ReadInt, ReadFloat etc.. though I could be wrong.

**Comment by DennisStanistan** [comment]
Also there are a lot of conflicts in this pull request because I made some additions that clash with yours. I hope it's okay that I take some parts of this pull request and add the necessary changes.

**Comment by berkay2578** [comment]
>I wouldn't recommend a single function for every type like Read or Write since it can slow down the reading & writing times
There will be a difference for sure but the difference is only seen when compared to the nanoseconds, since your way of doing it does exactly the same thing as this way but this utilizes the generic T. 

>I rather have it run fast as possible than having a simple & pretty function plus it is much faster when splitting them to single functions like ReadInt, ReadFloat etc..
I mean I'm no expert in programming and I sure as hell am as away from the programmer semantics as one can be but I think we both can agree that repetitive functions for each type is a beginner's mistake. Look at the code, your functions dumb down to r/w byte[] after converting the value and look at mine, which does the exact same thing but just uses object boxing.

I'd add though, that Marshal.SizeOf() _is_ unmanaged and will piss of the IL compiler. Fixing it as simple as defining consts for each type of reading those, it's really easy to do.

It still is your code though, I just am mainly trying to improve it.

**Comment by DennisStanistan** [comment]
>I think we both can agree that repetitive functions for each type is a beginner's mistake. Look at the code.
When it comes to squeezing as much as performance as I can, I throw the programming standards aside.

**Comment by berkay2578** [comment]
I will not remove the overhaul because I think it is the superior way of handling it. I'll stick to my fork your project your decision.

**Comment by DennisStanistan** [comment]
>I will not remove the overhaul because I think it is the superior way of handling it. I'll stick to my fork, your >project your decision.

Your overhaul is slower by 1ms, sometimes even by 5ms and while it may be more 'code friendly' or whatever you want to call it, overhaul is great when it improves the performance and not when you feel it's superior.
Experiment

> I removed 2 functions that do the same thing and created 1 function that does 9 calculations, why is that you're in love with multiple functions that do exactly the same thing?

Whoops, I missed the ConvertSpeed function.. my mistake.

>Also, you can easily overload Read/WriteString to have ASCII as default... you had different functions for >ASCII and Unicode encoding which wasn't optimal so I created the generic Encoding parameter.

Correct.

**Comment by berkay2578** [comment]
I'm getting _exactly_ the opposite results here.

Code: [(Here's the Clock class.)](https://ybin.me/p/14ce09990968fdad#EJZchurA8K7g+Iqn4RYLJO2qnFSMIpnf1xJN522du5c=)
```
using System;
using System.Windows.Forms;
using NFSScript;
using NFSScript.Core;
using addrs = NFSScript.Core.WorldAddresses;

namespace WorldTest
{
    public class WorldTest : Mod
    {
        public static string ByteArrayToString(byte[] ba)
        {
            string hex = BitConverter.ToString(ba);
            return hex.Replace("-", "");
        }

        public override void OnKeyDown(Keys key)
        {
            if (key == Keys.Y)
            {
                var memory = GameMemory.memory;
                Action resetMem = (() =>
                {
                    memory.WriteByte((IntPtr)memory.getBaseAddress + addrs.PlayerAddrs.NON_STATIC_CAR_COLLISION, 0x74);
                });

                Console.WriteLine("Starting: Old function on Stopwatch.");
                Clock.BenchmarkTime(() =>
                {
                    memory.WriteByte((IntPtr)memory.getBaseAddress + addrs.PlayerAddrs.NON_STATIC_CAR_COLLISION, 0xEB);
                    resetMem();
                }, 5);
                Console.WriteLine("Finished.");

                Console.WriteLine("Starting: Old function on CPU.");
                Clock.BenchmarkCpu(() =>
                {
                    memory.WriteByte((IntPtr)memory.getBaseAddress + addrs.PlayerAddrs.NON_STATIC_CAR_COLLISION, 0xEB);
                    resetMem();
                }, 5);
                Console.WriteLine("Finished.");
                //--

                Console.WriteLine("Starting: New function on Stopwatch.");
                Clock.BenchmarkTime(() =>
                {
                    memory.Write<byte>(addrs.PlayerAddrs.NON_STATIC_CAR_COLLISION, 0xEB, true);
                    resetMem();
                }, 5);
                Console.WriteLine("Finished.");

                Console.WriteLine("Starting: New function on CPU.");
                Clock.BenchmarkCpu(() =>
                {
                    memory.Write<byte>(addrs.PlayerAddrs.NON_STATIC_CAR_COLLISION, 0xEB, true);
                    resetMem();
                }, 5);
                Console.WriteLine("Finished.");
            }
        }
    }
}
```

Output:
```
Starting: Old function on Stopwatch.
0.3096ms
0.2379ms
0.2313ms
0.2291ms
0.2313ms
Finished.
Starting: Old function on CPU.
0ms
0ms
0ms
0ms
0ms
Finished.
Starting: New function on Stopwatch.
0.1505ms
0.1409ms
0.143ms
0.1439ms
0.1517ms
Finished.
Starting: New function on CPU.
0ms
0ms
0ms
0ms
0ms
```

**Comment by fallk** [comment]
You're both at least a little wrong :P 
1. You're doing too little iterations.[<sup>1</sup>](https://en.wikipedia.org/wiki/Entropy) You should do a few hundred, then get the average in nanos and that should suffice. (for an even more accurate, do a few hundred runs of a few hundred iterations and pick the best run)
2. If you really wanna go for the faster solution, non-generic functions are obviously the right choice (generic functions always store the argument in the stack and then get it back which is ever so slightly slower[<sup>2</sup>](http://stackoverflow.com/a/17308214)

I think you should just go for the generic version - chances are it's not gonna cause a bottleneck - but that's just my opinion, your project and all

I remain,
Yours truly,
a concerned mom

**Comment by berkay2578** [comment]
I like you, you make sense. You're right about the iterations, I just wanted something quick, the sum should still show closer but similar results though. Even if the generic functions are slower, it would only be by 1-2 milliseconds anyways, that's nearly nothing. People that write mods won't probably care about it, who would need precision to the nanoseconds in NFS games even when something like NFS: World requests UDP packets every 100ms...

**Comment by DennisStanistan** [comment]
Fine, I'll add the generic version soon enough.

**Pull request closed without merging**
